### 2. Create a vector with values ranging from 10 to 49.

In [49]:
import numpy as np
vector= np.arange(10,49)
print("original vector")
print(vector)

original vector
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [40]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print('\n3D Array : \n',x)



3D Array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [41]:
q=np.array([1,2,0,0,4,0])
q[q>0]

array([1, 2, 4])

### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [42]:
z=np.random.randint(1,100,(10,10))
print(z)
zmin,zmax=z.min(),z.max()
print('minimum value is:',zmin)
print('maximum value is:',zmax)

[[51 33 39  3  5 54 54  6 16 16]
 [65  3  9 84 16 80 12 15  8 88]
 [ 9 25 96 90 13 99 63 74 24 27]
 [37 68 15 79 31 25  6 68 73 22]
 [43 28 11 51 92 92 39 63 92 25]
 [46  9 75  7 45  8 26  7 48 34]
 [ 9 18 47 58 95  7 45 22 87  5]
 [44 38 23 80 74 72 62 78 88 94]
 [83 84 31 69 36 16 76 34 40 24]
 [ 3 19 62 77 45 14 74 53 69 58]]
minimum value is: 3
maximum value is: 99


### 6. Create a random vector of size 30 and find the mean value.


In [43]:
import numpy as np
vector = np.random.random(30)
print("original array:")
print(vector)
print('mean value is:',np.mean(vector))


original array:
[0.3302632  0.77710855 0.66563305 0.57888902 0.44160685 0.31084832
 0.80540051 0.21746219 0.03942083 0.15942566 0.97708567 0.55714188
 0.1983129  0.88192789 0.64462    0.91972208 0.07499067 0.58771147
 0.86581994 0.75657695 0.41559113 0.25068917 0.16959589 0.65962035
 0.13823637 0.86009354 0.11004988 0.28600362 0.60672288 0.76242631]
mean value is: 0.5016332258794876


### 1. Create a null vector of size 10 but the fifth value which is 1.

In [48]:
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])